const defaultFeatures = ["Password Reset", "Email Verification"]

export const templates = [
  {
    title: "Firebase + Next.js",
    description: "A complete authentication system usign best practices and Firebase.",
    features: ["Sign Up", "Login", "Production ready", ...defaultFeatures],
    slug: 'nextjs-firebase',
    isInProgress: false,
    difficulty: "Advanced",
    frontend: 'Next.js',
    backend: 'Firebase',
    authMethod: ['Email/Password', 'Google', 'Github'],
    techStack: ["Next.js", "Typescript", "Firebase", "Resend"],
    gitBranch: 'nextjs-firebase-email',
    docUrl: '/docs/templates/nextjs-firebase-email',
    githubUrl: 'https://github.com/authbuilders/templates',
  },
  {
    title: "JWT on Next.js",
    description: "Easily created jwt authentication system. Works only on development enviorment.",
    features: ["Sign Up", "Login", ...defaultFeatures],
    slug: 'nextjs-jwt',
    isInProgress: false,
    difficulty: "Beginner",
    frontend: 'Next.js',
    backend: 'jwt',
    authMethod: ['Email/Password',],
    techStack: ["Next.js", "Typescript", "Resend"],
    gitBranch: 'nextjs-firebase-email',
    docUrl: '/docs/templates/nextjs-firebase-email',
    githubUrl: 'https://github.com/authbuilders/templates',
  },
  {
    title: "Third Party Providers with jwt in Next.js",
    description: "Set up a authentication system with Google and Github providers",
    features: ["Sign Up", "Login", "Third Party Providers", ...defaultFeatures],
    slug: 'nextjs-jwt',
    isInProgress: true,
    difficulty: "Intermediate",
    frontend: 'Next.js',
    backend: 'jwt',
    authMethod: ['Google', 'Github'],
    techStack: ["Next.js", "Typescript", "Resend"],
    gitBranch: 'nextjs-firebase-email',
    docUrl: '/docs/templates/nextjs-firebase-email',
    githubUrl: 'https://github.com/authbuilders/templates',
  },
  {
    title: "Simple NextAuth implementation",
    description: "Complete authentication system using next auth",
    features: ["Sign Up", "Login", "Production Ready", ...defaultFeatures],
    slug: 'nextjs-nextauth',
    isInProgress: false,
    difficulty: "Beginner",
    frontend: 'Next.js',
    backend: 'nextAuth',
    authMethod: ['Email/Password', 'Google', 'Github'],
    techStack: ["Next.js", "Typescript", "Resend", "NextAuth"],
    gitBranch: 'nextjs-firebase-email',
    docUrl: '/docs/templates/nextjs-firebase-email',
    githubUrl: 'https://github.com/authbuilders/templates',
  },
  {
    title: "Simple NextAuth implemantation + Prisma",
    description: "Complete authentication system using nextAuth and prisma",
    features: ["Sign Up", "Login", "Production Ready", ...defaultFeatures],
    slug: 'nextjs-nextauth',
    isInProgress: true,
    difficulty: "Intermediate",
    frontend: 'Next.js',
    backend: 'nextAuth',
    authMethod: ['Prisma'],
    techStack: ["Next.js", "Typescript", "Resend", "NextAuth", "Prisma"],
    gitBranch: 'nextjs-firebase-email',
    docUrl: '/docs/templates/nextjs-firebase-email',
    githubUrl: 'https://github.com/authbuilders/templates',
  },
  {
    title: "Vite.js + Firebase",
    description: "A complete authentication system usign best practices and Firebase.",
    features: ["Sign Up", "Login", "Production Ready", ...defaultFeatures],
    slug: 'vitejs-firebase',
    isInProgress: true,
    difficulty: "Advanced",
    frontend: 'Vite',
    backend: 'Firebase',
    authMethod: ['Email/Password', 'Google', 'Github'],
    techStack: ["Vite.js", "Typescript", "Resend", "Firebase"],
    gitBranch: 'nextjs-firebase-email',
    docUrl: '/docs/templates/nextjs-firebase-email',
    githubUrl: 'https://github.com/authbuilders/templates',
  },
  {
    title: "JWT on Vite.js",
    description: "Easily created jwt authentication system. Works only on development enviorment.",
    features: ["Sign Up", "Login", ...defaultFeatures],
    slug: 'vitejs-jwt',
    isInProgress: true,
    difficulty: "Beginner",
    frontend: 'Vite',
    backend: 'jwt',
    authMethod: ['Email/Password', 'Google', 'Github'],
    techStack: ["Vite.js", "Typescript", "Resend"],
    gitBranch: 'nextjs-firebase-email',
    docUrl: '/docs/templates/nextjs-firebase-email',
    githubUrl: 'https://github.com/authbuilders/templates',
  },
];