export const templates = [
  {
    slug: 'nextjs-firebase',
    frontend: 'Next.js',
    backend: 'Firebase',
    authMethod: ['Email/Password', 'Google', 'Github'],
    gitBranch: 'nextjs-firebase-email',
    docUrl: '/docs/templates/nextjs-firebase-email',
    githubUrl: 'https://github.com/authbuilders/templates',
    isInProgress: false,
  },
  {
    slug: 'nextjs-jwt',
    frontend: 'Next.js',
    backend: 'jwt',
    authMethod: ['Email/Password',],
    gitBranch: 'nextjs-firebase-email',
    docUrl: '/docs/templates/nextjs-firebase-email',
    githubUrl: 'https://github.com/authbuilders/templates',
    isInProgress: false,
  },
  {
    slug: 'nextjs-jwt',
    frontend: 'Next.js',
    backend: 'jwt',
    authMethod: ['Google', 'Github'],
    gitBranch: 'nextjs-firebase-email',
    docUrl: '/docs/templates/nextjs-firebase-email',
    githubUrl: 'https://github.com/authbuilders/templates',
    isInProgress: true,
  },
  {
    slug: 'nextjs-nextauth',
    frontend: 'Next.js',
    backend: 'nextAuth',
    authMethod: ['Email/Password', 'Google', 'Github'],
    gitBranch: 'nextjs-firebase-email',
    docUrl: '/docs/templates/nextjs-firebase-email',
    githubUrl: 'https://github.com/authbuilders/templates',
    isInProgress: false,
  },
  {
    slug: 'nextjs-nextauth',
    frontend: 'Next.js',
    backend: 'nextAuth',
    authMethod: ['Prisma'],
    gitBranch: 'nextjs-firebase-email',
    docUrl: '/docs/templates/nextjs-firebase-email',
    githubUrl: 'https://github.com/authbuilders/templates',
    isInProgress: true,
  },
  {
    slug: 'vitejs-firebase',
    frontend: 'Vite',
    backend: 'Firebase',
    authMethod: ['Email/Password', 'Google', 'Github'],
    gitBranch: 'nextjs-firebase-email',
    docUrl: '/docs/templates/nextjs-firebase-email',
    githubUrl: 'https://github.com/authbuilders/templates',
    isInProgress: true,
  },
  {
    slug: 'vitejs-jwt',
    frontend: 'Vite',
    backend: 'jwt',
    authMethod: ['Email/Password', 'Google', 'Github'],
    gitBranch: 'nextjs-firebase-email',
    docUrl: '/docs/templates/nextjs-firebase-email',
    githubUrl: 'https://github.com/authbuilders/templates',
    isInProgress: true,
  },
  {
    slug: 'vitejs-nextauth',
    frontend: 'Vite',
    backend: 'nextAuth',
    authMethod: ['Email/Password', 'Google', 'Github'],
    gitBranch: 'nextjs-firebase-email',
    docUrl: '/docs/templates/nextjs-firebase-email',
    githubUrl: 'https://github.com/authbuilders/templates',
    isInProgress: true,
  },
];